### ISSUE TITLE
Too dumb to work out how to install this :(

### ISSUE THREAD

**Issue by ZythDr** [JustArion/Win11_PopupHost_Fix#1]
Hi, as the title suggests I'm way too stupid to figure out how to install this. I don't really know code at all, or how to "build" things unless it's straighforward and with step by step instructions :(

I tried creating Build.ps1 and ScheduleStartup.ps1 and copy pasted all the lines from the files on here and tried running those but that didn't seem to do anything at all... Sorry to be a pain in the ass, but could you help me out with steps to install this?

**Comment by JustArion** [comment]
My apologies on the vagueness. The latest build from github is available from the ([actions tab](https://github.com/JustArion/Win11_PopupHost_Fix/suites/10581551732/artifacts/526993883)) or via build, I forgot to add to the build steps that you'll need to download the repo via the download button or through the git command. Though the quickest steps would be through the actions link. I'll update the readme with detailed steps in a few minutes.

**Comment by JustArion** [comment]
Updated the repo with install ([requirements](https://github.com/JustArion/Win11_PopupHost_Fix#requirements-to-run--build))
and some improved ([build steps](https://github.com/JustArion/Win11_PopupHost_Fix#build-steps-simple))

Let me know if this helps ^^

**Comment by ZythDr** [comment]
Thanks a ton for the additional steps provided, I followed the steps and got it up and running now! 
Now to add this to startup do I need to do the same steps but with the ScheduleStartup instead of Build? Or could I just throw it into the startup folder on the start menu? (and get the UAC prompt pop up every boot ofc :P )

**Comment by JustArion** [comment]
Yes, though its up to you which one you'd want to do. 
Task Scheduler is more advanced but the program can work on things like Task Manager too.
or the simple option is the Startup folder yes (Win+R) ->`shell:Startup`

Having the program run as admin is optional though it will apply the fix to other programs that is not just Windows Explorer (Such as task manager)

**Comment by ZythDr** [comment]
I can't work out how to make the ScheduleStartup stuff to work, it tells me to drop the exe onto the terminal window but I can't seem to do that... oh well, I'll just add it to the Startup folder :D 

Thanks once again for all the help! And thanks for making this little script thingy in the first place, very annoying oversight by Microsoft!
